force-app/main/default/objects/Courier_Tracking__c/Courier_Tracking__c.object-meta.xml
<CustomObject>
    <label>Courier Tracking</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Courier Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courier Tracking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Courier_Tracking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Courier Tracking</relationshipLabel>
    <relationshipName>Courier_Tracking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Courier_Tracking__c/fields/Dispatched_On__c.field-meta.xml
<CustomField>
    <fullName>Dispatched_On__c</fullName>
    <label>Dispatched On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Courier_Tracking__c/fields/Received_By__c.field-meta.xml
<CustomField>
    <fullName>Received_By__c</fullName>
    <label>Received By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Courier_Tracking__c/fields/ReceivedBy_Phone__c.field-meta.xml
<CustomField>
    <fullName>ReceivedBy_Phone__c</fullName>
    <label>ReceivedBy Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Courier_Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CourierTrackingSystemController.cls
public class CourierTrackingSystemController {
    @AuraEnabled
    public static Account getAccountDetails(string recId){
        try{
            if(recId.startsWith('500')){
                recId=[select AccountId from Case where Id=: recId].AccountId;
            }
            return [select Id,Name,Card_Number__c,Account_Courier_Status__c,Tracking_Id__c, 
                    (select Id,Date__c,format(Time__c) formatedTime,Status__c from Courier_Tracking__r where Status__c IN ('Scheduled','Dispatched') LIMIT 1) 
                    from Account where Id =: recId];
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static Courier_Tracking__c createOrUpdateTracking(string trackingId, string accId, string scheduledDate, string scheduledTime){
        trackingId = (trackingId=='')?null:trackingId;
        Courier_Tracking__c cT = new Courier_Tracking__c(Id=trackingId, Account__c=accId, Status__c='Scheduled', Dispatched_On__c=null);
        cT.Date__c = Date.valueOf(scheduledDate);
        String[] strTimeSplit = scheduledTime.split(':');
        Time scheduledTimeFormatted = Time.newInstance(Integer.valueOf(strTimeSplit[0]),Integer.valueOf(strTimeSplit[1]),0,0);
        cT.Time__c = scheduledTimeFormatted;
        try{
            upsert cT;
            Account a = new Account(Id=accId,Account_Courier_Status__c='Scheduled',Tracking_Id__c='');
            update a;
            cT = [select Id,Date__c,format(Time__c) formatedTime,Status__c from Courier_Tracking__c where Id =: cT.Id];
            return cT;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static string confirmCourierPickup(string trackingId, string accId){
        try{
            Account a = new Account(Id=accId,Account_Courier_Status__c='Dispatched');
            update a;
            Courier_Tracking__c cT = new Courier_Tracking__c(Id=trackingId,Status__c='Dispatched',Dispatched_On__c=System.today());
            update cT;
            return 'dispatched';
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static string setCourierAsDelivered(string trackingId, string accId, string receivedBy, string receivedByPhone){
        try{
            Courier_Tracking__c cT = new Courier_Tracking__c(Id=trackingId, Status__c='Delivered', Received_By__c=receivedBy, ReceivedBy_Phone__c=receivedByPhone);
            update cT;
            Account a = new Account(Id=accId,Account_Courier_Status__c='Delivered',Account_Status__c='Active');
            update a;
            return 'delivered';
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static string getCourierStatus(string trackingId){
        try{
            return CourierAPICall.api_get(trackingId);
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static string callCourierService(string trackingId, string accId){
        try{
            return CourierAPICall.api_post(accId+'#'+trackingId+'#'+system.now(), UserInfo.getName(), '9832049910', 'Delhi', 'Patna');
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}